#!/bin/bash

CONFIG_FILES="$HOME/.config/waybar/config.json $HOME/.config/waybar/style.css $HOME/.cache/wal/colors-waybar.css"

trap "pkill waybar" EXIT

while true; do
    \cp -r $HOME/.cache/wal/colors-waybar.css $HOME/.config/waybar &
    waybar -c $HOME/.config/waybar/config.json -s $HOME/.config/waybar/style.css &
    inotifywait -e create,modify $CONFIG_FILES
    pkill waybar
done
